services:
  db:
    image: postgres:17.6
    shm_size: 128mb
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: nest-store-db
    volumes:
      - ./postgres:/var/lib/postgresql/data
